/** @type {import('tailwindcss').Config} */
module.exports = {
	content: ["./pages/**/*.{js,ts,jsx,tsx}", "./components/**/*.{js,ts,jsx,tsx}"],
	theme: {
		extend: {
			spacing: {
				18: "4.5rem",
				104: "28rem",
				112: "28rem",
				120: "30rem",
			},
		},
		fontFamily: {
			sans: [
				"IBM Plex Sans",
				"-apple-system",
				"BlinkMacSystemFont",
				"avenir next",
				"avenir",
				"helvetica neue",
				"helvetica",
				"Ubuntu",
				"roboto",
				"noto",
				"segoe ui",
				"arial",
				"sans-serif",
			],
			serif: [
				"IBM Plex Serif",
				"Iowan Old Style",
				"Apple Garamond",
				"Baskerville",
				"Times New Roman",
				"Droid Serif",
				"Times",
				"Source Serif Pro",
				"serif",
				"Apple Color Emoji",
				"Segoe UI Emoji",
				"Segoe UI Symbol",
			],
			mono: [
				"IBM Plex Mono",
				"Menlo",
				"Consolas",
				"Monaco",
				"Liberation Mono",
				"Lucida Console",
				"monospace",
			],
		},
	},
	plugins: [],
};
