import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import { useRouter } from "next/router";
import Link from "next/link";

import "@fontsource/ibm-plex-mono/latin.css";
import "@fontsource/ibm-plex-sans/latin.css";
import "@fontsource/ibm-plex-serif/latin.css";

const Home: NextPage = () => {
	const router = useRouter();

	return (
		<div className="mx-auto my-28">
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<main className="flex flex-col space-y-40">
				<div className="flex flex-col space-y-20">
					<div className="max-w-4xl mx-auto flex flex-col space-y-12">
						<h1
							className="text-8xl font-bold flex-1 bg-gradient-to-r from-indigo-600 to-indigo-200 bg-clip-text"
							aria-label="A Programmable Workspace for Developers, Site Reliability Engineers, and Infrastructure Teams."
							style={{
								WebkitBackgroundClip: "text",
								backgroundClip: "text",
								color: "rgba(0,0,0,0);",
							}}
						>
							Infrastructure
							<br />
							Stuff
						</h1>

						<div className="hero-subheading text-2xl text-indigo-900 font-normal leading-relaxed">
							A{" "}
							<Link href="https://discord.gg/JHc2ZrmaeD">
								<a target="_blank" rel="noreferrer">
									public Discord server
								</a>
							</Link>{" "}
							and <Link href="/listen">podcast</Link> focused on internet
							infrastructure—industry trends, academic research, startups,{" "}
							<em>etc</em>.
						</div>

						<div className="flex flex-row space-x-24 text-indigo-600">
							<div className="flex flex-col space-y-4">
								<div className="text-indigo-500 font-medium font-mono underline decoration-2 underline-offset-4 decoration-indigo-400 decoration-dotted">
									Discord
								</div>
								<div className="flex flex-row space-x-8 items-center">
									<Link href="https://discord.gg/JHc2ZrmaeD">
										<a
											className="cursor-pointer flex flex-row no-underline hover:no-underline space-x-2 items-center bg-indigo-500 hover:bg-indigo-600 active:bg-indigo-700 text-base text-white hover:text-white px-3 py-2 rounded-md font-medium focus:outline-none focus:ring-4 ring-indigo-300"
											target="_blank"
											rel="noreferrer"
										>
											<Image
												src="/discord-white.svg"
												alt="Join Discord Channel"
												width={24}
												height={24}
											/>{" "}
											<div>Join Channel</div>
										</a>
									</Link>
								</div>
							</div>
							<div className="flex flex-col space-y-4">
								<div className="text-indigo-500 font-medium font-mono underline decoration-2 underline-offset-4 decoration-indigo-400 decoration-dotted">
									Podcast
								</div>
								<div className="flex flex-row space-x-8 items-center">
									<Link href="/listen">
										<a className="cursor-pointer flex flex-row space-x-2 no-underline hover:no-underline items-center border border-indigo-800 bg-transparent hover:bg-slate-200 active:bg-slate-300 text-base text-indigo-800 active:text-black px-3 py-2 rounded-md font-medium focus:outline-none focus:ring-4 ring-indigo-300">
											<Image
												src="/play--filled--alt.svg"
												alt="Listen to Podcast"
												width={16}
												height={16}
											/>
											<div>Listen</div>
										</a>
									</Link>
								</div>
							</div>
							<div className="hero-subheading flex flex-col space-y-2">
								<div className="text-indigo-500 font-medium font-mono underline decoration-2 underline-offset-4 decoration-indigo-400 decoration-dotted">
									Hosts
								</div>
								<Link href="https://twitter.com/martin_casado">
									<a className="text-xl" target="_blank" rel="noreferrer">
										Martin Casado
									</a>
								</Link>
								<Link href="https://twitter.com/tnachen">
									<a className="text-xl" target="_blank" rel="noreferrer">
										Tim Chen
									</a>
								</Link>
								<Link href="https://twitter.com/hausdorff_space">
									<a className="text-xl" target="_blank" rel="noreferrer">
										Alex Clemmer
									</a>
								</Link>
							</div>
						</div>
					</div>
				</div>

				{/* <div className=" mx-96 flex flex-row">
					<div className="max-w-4xl flex flex-col space-y-8 text-2xl text-indigo-900 font-normal leading-relaxed">
						<h1>Why?</h1>

						<div>
							Infrastructure engineering is the{" "}
							<span className="bg-gradient-to-r from-yellow-200 to-cyan-200 px-2">
								most leveraged knowledge work in history.
							</span>{" "}
						</div>
						<div>
							It is the reason consumer internet applications like Google and Facebook
							are some of the most scalable businesses in history.
						</div>
						<div>
							Offered as a standalone product, infrastructure businesses like AWS and
							Snowflake are themselves some of the fastest-growing and largest
							businesses in the world.
						</div>
					</div>
				</div> */}
			</main>

			<footer>
				{/* <a
					href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
					target="_blank"
					rel="noopener noreferrer"
				>
					Powered by{" "}
					<span>
						<Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
					</span>
				</a> */}
			</footer>
		</div>
	);
};

export default Home;
